/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Numeric = ColumnType<string, number | string, number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Meal {
  id: Generated<number>
  name: string
  priceEur: Numeric
  type: string
}

export interface Menu {
  date: Timestamp
  id: Generated<number>
  mealId: number
}

export interface Order {
  date: Timestamp
  id: Generated<number>
  mainMealId: number | null
  soupMealId: number | null
  userId: number
}

export interface Role {
  id: Generated<number>
  name: string
}

export interface User {
  email: string
  id: Generated<number>
  name: string
  password: string
  roleId: number
}

export interface DB {
  meal: Meal
  menu: Menu
  order: Order
  role: Role
  user: User
}
