@localUrl= http://localhost:3000/api/v1/trpc/
@adminAccessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJyb2xlTmFtZSI6ImFkbWluIn0sImlhdCI6MTc1MTUzOTE0NywiZXhwIjoxNzUyMTQzOTQ3fQ.C4jlPfcN0Zh2y5vlS8iXE10YLIO4cGgAiEycZAbYxuw
@chefAccessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiY2hlZiIsInJvbGVOYW1lIjoiY2hlZiJ9LCJpYXQiOjE3NTE1NDAwNjEsImV4cCI6MTc1MjE0NDg2MX0.3YWrD4BvgrSMmiF_32PAwkbjE8evGOHVRRRWVk43OCQ
@userAccessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMDMzLCJuYW1lIjoidXNlcjEyMyIsInJvbGVOYW1lIjoidXNlciJ9LCJpYXQiOjE3NTE1NjY3ODcsImV4cCI6MTc1MjE3MTU4N30.Mqw8qIebkwS2He-M5AzfYQlLUog3rNMsQxEvooQno8E



#####################################


### standard user is signing up
POST {{localUrl}}/user.signup
Content-Type: application/json

{
  "json": {
    "email": "user1234@email.com",
    "password": "user12345",
    "name": "user123"
  }
}

### login user

POST {{localUrl}}/user.login
Content-Type: application/json

{
  "json": {
    "email": "user1234@email.com",
    "password": "user12345"
  }
}

### change password

POST {{localUrl}}/user.changePassword
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "oldPassword": "user12345",
    "newPassword": "user123456789",
    "confirmNewPassword": "user123456789"
  }
}

#############################################

### standard user to delete - signing up

POST {{localUrl}}/user.login
Content-Type: application/json

{
  "json": {
    "email": "userDelete@email.com",
    "password": "user12345"
  }
}

### delete user

POST {{localUrl}}/user.removeUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMjUsIm5hbWUiOiJ1c2VyMTIzIiwicm9sZU5hbWUiOiJ1c2VyIn0sImlhdCI6MTc1MTU0NDQxMywiZXhwIjoxNzUyMTQ5MjEzfQ.MWK0pWJFEgWxC8ojEzIo105zgfcVMT0EwWWu8k41EFg
Content-Type: application/json

{
  "json": {
    "password": "user12345"
  }
}

###############################################

### user - creates orders

POST {{localUrl}}/order.createOrderForMenu
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "userId": "123",
    "date": "2025-08-01",
    "soupMealId": "1",
    "mainMealId": "2"
  }
}

### user - updates orders

POST {{localUrl}}/order.updateOrder
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "userId": "123",
    "date": "2025-08-05",
    "soupMealId": "1"
  }
}

###########################

### user - get monthly costs


POST {{localUrl}}/order.getMonthlyCosts
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "year": "2025",
    "month": "8"
  }
}

##############################
### user - get monthly costs


POST {{localUrl}}/order.getOrderByUserDates
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "dates": ["2025-08-01", "2025-08-05"]
  }
}


######################
### helper functions

###

POST {{localUrl}}/meal.createMeal
Authorization: Bearer {{chefAccessToken}}
Content-Type: application/json

{
  "json": {
    "name": "macaroni soup",
    "priceEur": "3.05",
    "type": "soup"
  }
}

###
POST {{localUrl}}/meal.createMeal
Authorization: Bearer {{chefAccessToken}}
Content-Type: application/json

{
  "json": {
    "name": "french fries with fish nuget",
    "priceEur": "3.05",
    "type": "main"
  }
}

###
POST {{localUrl}}/menu.addMenuMeal
Authorization: Bearer {{chefAccessToken}}
Content-Type: application/json

{
  "json": {
    "date": "2025-08-05",
    "mealId": "4"
  }
}

###
POST {{localUrl}}/menu.addMenuMeal
Authorization: Bearer {{chefAccessToken}}
Content-Type: application/json

{
  "json": {
    "date": "2025-08-05",
    "mealId": "5"
  }
}

###
POST {{localUrl}}/menu.addMenuMeal
Authorization: Bearer {{chefAccessToken}}
Content-Type: application/json

{
  "json": {
    "date": "2025-08-05",
    "mealId": "1"
  }
}

###
POST {{localUrl}}/order.createOrderForMenu
Authorization: Bearer {{userAccessToken}}
Content-Type: application/json

{
  "json": {
    "userId": "123",
    "date": "2025-08-05",
    "soupMealId": "4",
    "mainMealId": "5"
  }

